# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.2.2"

pre_release = true

preface = """\
"""

[notes]

    [notes.kernel_modules]
        title = "Kernel Modules"
        description = """\
Talos now supports settings kernel module parameters.

Eg:

```yaml
machine:
  kernel:
    modules:
      - name: "br_netfilter"
        parameters:
          - nf_conntrack_max=131072
```
"""

    [notes.sbc]
        title = "Nano Pi R4S"
        description = """\
Talos now supports the Nano Pi R4S SBC.
"""

    [notes.updates]
        title = "Component Updates"
        description="""\
* Flannel: v0.19.2
* CoreDNS: v1.9.4
* etcd: v3.5.5
* Linux: 5.15.68
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
