# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.1.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.network-bridge]
        title = "Network bridge support"
        description = """\
Talos now supports configuring Linux bridges. It can be configured in the machine config like the following:
```yaml
spec:
  machine:
    network:
      interfaces:
        - interface: br0
          bridge:
            stp:
              enabled: true
            interfaces:
              - eth0
              - eth1
```

See [documentation](https://www.talos.dev/v1.2/reference/configuration/#bridge) for more details.
"""

    [notes.network-vlan-cmdline]
        title = "VLAN support in cmdline arguments"
        description = """\
Talos now supports dracut-style `vlan` kernel argument to allow
installing Talos Linux in networks where ports are not tagged
with a default VLAN:

```
vlan=eth1.5:eth1 ip=172.20.0.2::172.20.0.1:255.255.255.0::eth1.5:::::
```

"""

    [notes.updates]
        title = "Component Updates"
        description="""\
* Linux: 5.15.57

Talos is built with Go 1.18.4.
"""

    [notes.talos-config-kernel-param-variable-substitution]
        title = "Variable substitution for URL query parameter in the talos.config kernel parameter"
        description="""\
        The kernel parameter talos.config can now substitute system information into placeholders inside its URL query values. This example shows all supported variables:

```http://example.com/metadata?h=${hostname}&m=${mac}&s=${serial}&u=${uuid}```
"""

    [notes.strategic-merge]
        title = "Strategic merge machine configuration patching"
        description="""\
In addition to JSON (RFC6902) patches Talos now supports [strategic merge patching](https://www.talos.dev/v1.2/talos-guides/configuration/patching/).

For example, machine hostname can be set with the following patch:

```yaml
machine:
  network:
    hostname: worker1
```

Patch format is detected automatically.
"""

    [notes.gen-secrets-from-pki]
        title = "Generating Talos secrets from PKI directory"
        description="""\
It is now possible to generate a secrets bundle from a Kubernetes PKI directory (e.g. `/etc/kubernetes/pki`).

You can also specify a bootstrap token to be used in the secrets bundle.

This secrets bundle can then be used to generate a machine config.

This facilitates migrating clusters (e.g. created using `kubeadm`) to Talos.

```
talosctl gen secrets --kubernetes-bootstrap-token znzio1.1ifu15frz7jd59pv --from-kubernetes-pki /etc/kubernetes/pki
talosctl gen config --with-secrets secrets.yaml my-cluster https://172.20.0.1:6443
```
"""

    [notes.packet-capture]
        title = "Packet Capture"
        description="""\
Talos now supports capturing packets on a network interface with `talosctl pcap` command:

  talosctl pcap --interface eth0
"""

    [notes.stable-hostname]
        title = "Stable Default Hostname"
        description="""\
Talos now generates the default hostname (when there is no explicitly specified hostname) for the nodes based on the
node id (e.g. `talos-2gd-76y`) instead of using the DHCP assigned IP address (e.g. `talos-172-20-0-2`).

This ensures that the node hostname is not changed when DHCP assigns a new IP to a node.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
